In [2]:
import pandas as pd
import numpy as np

In [3]:
# Creating a normal dataset

study_hours = np.random.normal(10,2,1000)
sleeping_hours = np.random.normal(10,2,1000)

passed = (study_hours + np.random.normal(0,1,1000)) > (sleeping_hours + np.random.normal(0,1,1000))
passed = passed.astype(int)

In [4]:
df = pd.DataFrame({'study_hours': study_hours,"sleeping_hours": sleeping_hours, "passed" :passed})
df['passed'].value_counts()

passed
1    502
0    498
Name: count, dtype: int64

In [5]:
df

study_hours  sleeping_hours  passed
0      10.578026       11.086077       0
1      14.606853        8.728411       1
2       6.979615        8.160380       0
3       6.562913        6.865646       1
4      10.272748        8.146922       1
..           ...             ...     ...
995     8.807053        7.798450       1
996    12.950478       11.453588       0
997     6.846708        9.881019       0
998    10.801557        9.096613       0
999     8.987640       11.007610       0

[1000 rows x 3 columns]

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [7]:
x = df[['study_hours','sleeping_hours']]
y = df['passed']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.2, random_state=20)

In [8]:
log_model = LogisticRegression()
log_model.fit(x_train,y_train)

LogisticRegression()

In [9]:
y_pred = log_model.predict(x_test)

In [10]:
y_pred

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0])

In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [12]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))
print("Accuracy :- ",accuracy_score(y_test,y_pred))
print("Precision :- ",precision_score(y_test,y_pred))
print("Recall :- ",recall_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

confusion matrix
[[ 67  21]
 [  9 103]]
Accuracy :-  0.85
Precision :-  0.8306451612903226
Recall :-  0.9196428571428571
              precision    recall  f1-score   support

           0       0.88      0.76      0.82        88
           1       0.83      0.92      0.87       112

    accuracy                           0.85       200
   macro avg       0.86      0.84      0.84       200
weighted avg       0.85      0.85      0.85       200



In [13]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.76      0.82        88
           1       0.83      0.92      0.87       112

    accuracy                           0.85       200
   macro avg       0.86      0.84      0.84       200
weighted avg       0.85      0.85      0.85       200



# SVM

In [14]:
from sklearn import datasets
import pandas as pd
 
# Importing iris data

iris = datasets.load_iris()

In [15]:
df = pd.DataFrame(data =iris.data, columns = iris.feature_names )
df["species"] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                  5.1               3.5                1.4               0.2  \
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [16]:
x = df.drop(['species'], axis = 1)
y = df['species']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.1, random_state=50)

In [17]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [18]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

confusion matrix
[[6 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         5

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

