In [19]:
import pandas as pd
import numpy as np

In [20]:
# Creating a normal dataset

study_hours = np.random.normal(10,2,1000)
sleeping_hours = np.random.normal(10,2,1000)

passed = (study_hours + np.random.normal(0,1,1000)) > (sleeping_hours + np.random.normal(0,1,1000))
passed = passed.astype(int)

In [21]:
df = pd.DataFrame({'study_hours': study_hours,"sleeping_hours": sleeping_hours, "passed" :passed})
df['passed'].value_counts()

passed
1    509
0    491
Name: count, dtype: int64

In [22]:
df

study_hours  sleeping_hours  passed
0      10.190496        9.910561       1
1      11.812692        8.741881       1
2      10.212299       10.323295       0
3      10.438836        7.071106       1
4      10.252622        9.759113       1
..           ...             ...     ...
995     8.335655       10.623606       0
996     7.674894        8.612647       0
997     8.324780        7.484607       1
998    11.809650        7.107920       1
999     4.319296       10.544004       0

[1000 rows x 3 columns]

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [24]:
x = df[['study_hours','sleeping_hours']]
y = df['passed']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.2, random_state=20)

In [25]:
log_model = LogisticRegression()
log_model.fit(x_train,y_train)

LogisticRegression()

In [26]:
y_pred = log_model.predict(x_test)

In [27]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0])

In [28]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [29]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))
print("Accuracy :- ",accuracy_score(y_test,y_pred))
print("Precision :- ",precision_score(y_test,y_pred))
print("Recall :- ",recall_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

confusion matrix
[[92 12]
 [12 84]]
Accuracy :-  0.88
Precision :-  0.875
Recall :-  0.875
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       104
           1       0.88      0.88      0.88        96

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88       104
           1       0.88      0.88      0.88        96

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



# SVM

In [31]:
from sklearn import datasets
import pandas as pd
 
# Importing iris data

iris = datasets.load_iris()

In [32]:
df = pd.DataFrame(data =iris.data, columns = iris.feature_names )
df["species"] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                  5.1               3.5                1.4               0.2  \
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [33]:
x = df.drop(['species'], axis = 1)
y = df['species']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.1, random_state=50)

In [34]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [35]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

confusion matrix
[[6 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         5

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

